name: package.yml

on: 
  workflow_dispatch:
    
jobs:
        
  myjob:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        package_debug: [true, false]
    runs-on: ${{ matrix.os }}
    steps:
      # Check out source code
      - name: Check Out Source Code
        uses: actions/checkout@v4
      
      - name: Package Code + Dependencies
        uses: fortify/github-action/package@v1
        env:
          PACKAGE_OPTS: "-bt mvn"
          DO_PACKAGE_DEBUG: ${{matrix.package_debug}}
